---
- id: ansible-molecule-lint
  name: Ansible YAML lint check
  language: docker_image
  exclude: .*
  always_run: true
  entry: lowess/drone-molecule:latest molecule lint

- id: ansible-molecule-syntax
  name: Ansible systax check
  language: docker_image
  exclude: .*
  always_run: true
  entry: lowess/drone-molecule:latest molecule syntax

- id: prepare-commit-message
  name: Prepare commit message
  entry: prepare-commit-message
  language: python
  pass_filenames: true
  always_run: true
  types: [text]

- id: terragrunt-hclfmt
  name: Terragrunt HCL format
  files: \.hcl$
  language: docker_image
  entry: lowess/terragrunt:0.12.24 terragrunt hclfmt

- id: terraform-fmt
  name: Terraform format
  files: \.tf$
  exclude: \.+.terraform\/.*$
  language: docker_image
  always_run: true
  entry: lowess/terragrunt:0.12.24 terraform fmt

- id: jinja2-render-template
  name: Render jinja2 template
  language: docker_image
  exclude: .*
  always_run: true
  entry: lowess/yasha:latest

- id: npm-test
  name: Run npm tests
  language: system
  files: '\.test.(ts|tsx)$'
  always_run: true
  entry: npm run test
